"use client";

import { useEffect, useState } from "react";
import * as XLSX from "xlsx";

type Row={id:string;source:string;supplier:string;orderNo:string;sku:string;qty:number;billNo:string;dispatchDate:string;daysInTransit:number;receivedInWh1:string;receivedInUae:string;orderStatus:string;image:string};
type Summary={totalOrders:number;totalLines:number;totalPcs:number;totalSuppliers:number};
const empty:Summary={totalOrders:0,totalLines:0,totalPcs:0,totalSuppliers:0};
const fmt=(v:string)=>new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Dubai",day:"2-digit",month:"short",year:"numeric"}).format(new Date(v));

export default function IndiaUaeTransitReportPage(){
 const [supplier,setSupplier]=useState(""),[suppliers,setSuppliers]=useState<string[]>([]),[rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState(empty),[loading,setLoading]=useState(false),[selectedImage,setSelectedImage]=useState<string|null>(null);
 async function load(s=supplier){setLoading(true);try{const q=s?`?supplier=${encodeURIComponent(s)}`:"";const r=await fetch(`/api/reports/india-uae-transit${q}`,{cache:"no-store"});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Report load failed");setSuppliers(d.suppliers||[]);setRows(d.rows||[]);setSummary(d.summary||empty)}catch(e){alert(e instanceof Error?e.message:"Report load failed");setRows([]);setSummary(empty)}finally{setLoading(false)}}
 useEffect(()=>{load("")},[]);
 function excel(){if(!rows.length)return alert("No India to UAE transit delays to export");const data=rows.map(r=>({Supplier:r.supplier,"Order No":r.orderNo,SKU:r.sku,Qty:r.qty,"Dispatch Date":fmt(r.dispatchDate),"Bill No":r.billNo,"Days In Transit":r.daysInTransit,"Order Status":r.orderStatus||"","India Dispatched":r.receivedInWh1,"UAE Received":r.receivedInUae||"No",Source:r.source}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"India UAE Transit");XLSX.writeFile(wb,`India_UAE_Transit_Delays_${supplier||"all"}.xlsx`)}
 return <div className="space-y-6">
  <div><h1 className="text-3xl font-black text-slate-950">India → UAE Transit Delays</h1><p className="mt-1 text-sm font-bold text-slate-500">India se dispatched orders jo 7 din ke baad bhi UAE receive nahi hue.</p></div>
  <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm flex flex-wrap gap-3 items-end"><div className="min-w-[260px] flex-1"><label className="text-xs font-black uppercase text-slate-500">Supplier</label><select value={supplier} disabled={loading} onChange={async e=>{setSupplier(e.target.value);await load(e.target.value)}} className="mt-1 h-12 w-full rounded-xl border px-3 font-bold"><option value="">All Suppliers</option>{suppliers.map(s=><option key={s}>{s}</option>)}</select></div><button onClick={()=>load()} disabled={loading} className="h-12 rounded-xl bg-blue-600 px-5 font-black text-white">{loading?"Loading...":"Refresh"}</button><button onClick={excel} disabled={!rows.length||loading} className="h-12 rounded-xl bg-emerald-600 px-5 font-black text-white disabled:opacity-40">Excel</button><button onClick={()=>window.print()} disabled={!rows.length||loading} className="h-12 rounded-xl bg-slate-900 px-5 font-black text-white disabled:opacity-40">Print</button></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Orders",summary.totalOrders],["Total Lines",summary.totalLines],["Pending PCS",summary.totalPcs],["Suppliers Affected",summary.totalSuppliers]].map(([l,v])=><div key={String(l)} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs font-black uppercase text-slate-500">{l}</p><p className="mt-1 text-xl font-black">{v}</p></div>)}</div>
  <div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="text-lg font-black">India → UAE Delays (7+ Days)</h2><p className="text-xs font-bold text-slate-500">{rows.length?`${rows.length} transit order line(s) found`:"No India to UAE transit delays found"}</p></div>
   <div className="overflow-auto"><table className="w-full min-w-[1200px] text-sm"><thead className="bg-slate-200"><tr>{["Image","Order No","SKU","Qty","Supplier","Dispatch Date","Bill No","Days In Transit","Order Status","India Dispatch","UAE Received","Source"].map(x=><th key={x} className="px-4 py-3 text-left">{x}</th>)}</tr></thead><tbody>
   {rows.map((r,i)=><tr key={r.id} className={`border-t ${i%2?"bg-slate-50":"bg-white"} hover:bg-blue-50`}><td className="px-4 py-3">{r.image?<button onClick={()=>setSelectedImage(r.image)}><img src={r.image} alt={r.sku||"Product"} className="h-16 w-16 rounded-xl object-cover"/></button>:<span className="text-xs text-slate-400">No Image</span>}</td><td className="px-4 py-3 font-black">{r.orderNo}</td><td className="px-4 py-3 font-bold">{r.sku||"-"}</td><td className="px-4 py-3 text-center font-black">{r.qty}</td><td className="px-4 py-3 font-bold">{r.supplier}</td><td className="px-4 py-3 font-bold">{fmt(r.dispatchDate)}</td><td className="px-4 py-3 font-bold">{r.billNo}</td><td className="px-4 py-3 text-center"><span className="rounded-full bg-red-100 px-3 py-1 text-xs font-black text-red-700">{r.daysInTransit} days</span></td><td className="px-4 py-3 font-black">{r.orderStatus||"—"}</td><td className="px-4 py-3 text-center text-emerald-700 font-black">Yes</td><td className="px-4 py-3 text-center text-amber-700 font-black">{r.receivedInUae||"No"}</td><td className="px-4 py-3 font-bold">{r.source}</td></tr>)}
   {!loading&&!rows.length&&<tr><td colSpan={12} className="px-4 py-12 text-center font-bold text-slate-500">No orders found that were dispatched from India and remain unreceived in UAE for 7+ days.</td></tr>}
   {loading&&<tr><td colSpan={12} className="px-4 py-12 text-center font-black text-blue-600">Loading India → UAE transit report...</td></tr>}
   </tbody></table></div></div>
  {selectedImage&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4" onClick={()=>setSelectedImage(null)}><img src={selectedImage} alt="Product preview" className="max-h-[90vh] max-w-[90vw] rounded-2xl object-contain"/></div>}
 </div>
}
