import { DeleteObjectsCommand, ListObjectsV2Command, S3Client } from "@aws-sdk/client-s3";
import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function getConfig(){const accountId=process.env.R2_ACCOUNT_ID;const accessKeyId=process.env.R2_ACCESS_KEY_ID;const secretAccessKey=process.env.R2_SECRET_ACCESS_KEY;const bucketName=process.env.R2_BUCKET_NAME;const publicUrl=process.env.R2_PUBLIC_URL;if(!accountId||!accessKeyId||!secretAccessKey||!bucketName||!publicUrl)throw new Error("R2 environment variables are missing");return{accountId,accessKeyId,secretAccessKey,bucketName,publicUrl:publicUrl.replace(/\/$/,"")};}
function getClient(c:ReturnType<typeof getConfig>){return new S3Client({region:"auto",endpoint:`https://${c.accountId}.r2.cloudflarestorage.com`,credentials:{accessKeyId:c.accessKeyId,secretAccessKey:c.secretAccessKey}});}
async function requireUser(){const session=await getSession();if(!session)throw{status:401,message:"Not authenticated"};return session;}
function marketFromFolder(folder:string){return folder.replace(/-/g," ");}
function currencyFromMarket(market:string){const n=market.toLowerCase();if(n==="uae")return"AED";if(n==="qatar")return"QAR";if(n==="mauritius")return"MUR";if(n==="saudi arabia")return"SAR";if(n==="oman")return"OMR";if(n==="kuwait")return"KWD";if(n==="bahrain")return"BHD";if(n==="international")return"USD";return"";}

export async function GET(){try{await requireUser();const c=getConfig();const client=getClient(c);const objects:Array<{key:string;size:number;lastModified:string}>=[];let token:string|undefined;do{const r=await client.send(new ListObjectsV2Command({Bucket:c.bucketName,Prefix:"products/",ContinuationToken:token,MaxKeys:1000}));for(const o of r.Contents||[]){if(!o.Key||o.Key.endsWith("/"))continue;objects.push({key:o.Key,size:Number(o.Size||0),lastModified:o.LastModified?.toISOString()||""});}token=r.IsTruncated?r.NextContinuationToken:undefined;}while(token);
const map=new Map<string,any>();for(const o of objects){const parts=o.key.split("/");const sku=parts[1]||"UNSORTED";const folder=parts[2]||"Unsorted";const market=marketFromFolder(folder);const currency=currencyFromMarket(market);const groupKey=`${sku}:${folder}`;const url=`${c.publicUrl}/${o.key}`;const g=map.get(groupKey)||{sku,market,currency,count:0,totalSize:0,coverUrl:url,images:[]};g.count++;g.totalSize+=o.size;g.images.push({key:o.key,url,sku,market,currency,size:o.size,lastModified:o.lastModified});map.set(groupKey,g);}const groups=Array.from(map.values()).map((g:any)=>({...g,images:g.images.sort((a:any,b:any)=>b.lastModified.localeCompare(a.lastModified))})).sort((a:any,b:any)=>a.sku.localeCompare(b.sku));return NextResponse.json({success:true,groups});}catch(e:any){return NextResponse.json({success:false,message:e?.message||"Gallery load failed"},{status:e?.status||500});}}

export async function DELETE(request:Request){try{const session=await requireUser();const permission=session.selectedBase||session.permissions?.[0];const canDelete=session.role==="Admin"||Boolean(session.superAdmin)||Boolean(permission?.canDelete);if(!canDelete)return NextResponse.json({success:false,message:"Only Admin or users with delete permission can delete images"},{status:403});const body=await request.json();const key=String(body.key||"").trim();const prefix=String(body.prefix||"").trim();if(!key&&!prefix)return NextResponse.json({success:false,message:"Image key or folder prefix is required"},{status:400});const c=getConfig();const client=getClient(c);const keys:string[]=[];if(key)keys.push(key);else{let token:string|undefined;do{const r=await client.send(new ListObjectsV2Command({Bucket:c.bucketName,Prefix:prefix,ContinuationToken:token,MaxKeys:1000}));keys.push(...(r.Contents||[]).map(o=>o.Key||"").filter(Boolean));token=r.IsTruncated?r.NextContinuationToken:undefined;}while(token);}for(let i=0;i<keys.length;i+=1000){const batch=keys.slice(i,i+1000);await client.send(new DeleteObjectsCommand({Bucket:c.bucketName,Delete:{Objects:batch.map(Key=>({Key})),Quiet:true}}));}return NextResponse.json({success:true,deletedCount:keys.length});}catch(e:any){return NextResponse.json({success:false,message:e?.message||"Delete failed"},{status:e?.status||500});}}
